### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by FrittenKeeZ** [dwarfhq/laravel-meilitools#1]
**Commands:**
- [x] Reset Index
- [x] Reset Model

**Index**
- [x] Add `__soft_deleted` to filterable attributes automatically for soft deleted models

**Readme**
- [ ] Usage examples

**Support:**
- [x] Optional Scout dependency for usage with sites like Statamic
- [ ] Filter Builder
  - [ ] Extend Scout Builder and Searchable to enable advanced filtering 
  - [ ] Add special datetime handling for easier filtering ???
  - [ ] Add support for `0.29` filters and matching strategy
  - [ ] Ensure order works with `_geoPoint`
- [ ] Drop PHP 7.4 support
- [x] Laravel 10 support
- [ ] Laravel Scout 10 support

**Testing:**
- [ ] Replace unit tests with Pest

**Comment by rico** [comment]
> Add __soft_deleted to filterable attributes automatically for soft deleted models

That would be awesome ...

**Comment by FrittenKeeZ** [comment]
> > Add __soft_deleted to filterable attributes automatically for soft deleted models
> 
> This would be awesome ...

@rico I'll tackle this as the next update :)

**Comment by adgower** [comment]
@FrittenKeeZ any updates on bumping package for laravel 10?

**Comment by FrittenKeeZ** [comment]
@adgower I just added Laravel 10 support in `0.3.5` - Scout 10 is a bigger change though

**Comment by AlejandroAkbal** [comment]
Eagerly awaiting for `Extend Scout Builder and Searchable to enable advanced filtering`!

**Comment by FrittenKeeZ** [comment]
@AlejandroAkbal I have most of it working in a local branch, but I just need time to make unit tests and make sure everything works :)
